services:
  backend:
    image: ${DOCKER_USERNAME}/nuriwoolim-backend:latest
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
      - FRONT_URL=${FRONT_URL}
      - EMAIL=${EMAIL}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - PRIVATE_ORIGINS=${PRIVATE_ORIGINS}
      - SERVER_PORT=8080
    networks:
      - app-network
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT}
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_ROOT}" ]
      interval: 10s
      timeout: 5s
      retries: 10
volumes:
  db-data:

networks:
  app-network:
    driver: bridge